### ISSUE TITLE
Issue running example project on iOS

### ISSUE THREAD

**Issue by trilom** [jadennn/flutter_ijk#1]
When I try to run project on iOS I get this output:

```
  ~/repos/flutter_iJK/example     master  flutter run -d all                          4761  12:41:15 
Running "flutter packages get" in example...                 2.2s
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                       1.5s
Starting Xcode build...
 ├─Assembling Flutter resources...                    1.9s

 └─Compiling, linking and signing...                  0.9s

Xcode build done.                                            8.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: warning: ignoring file /Users/bkillian/repos/flutter_ijk/ios/IJKMediaFramework.framework/IJKMediaFramework,
    file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73
    0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64):
    /Users/bkillian/repos/flutter_ijk/ios/IJKMediaFramework.framework/IJKMediaFramework
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_IJKFFOptions", referenced from:
          objc-class-ref in libflutter_ijk.a(FlutterIjkPlugin.o)
      "_IJKMPMoviePlayerPlaybackDidFinishNotification", referenced from:
          -[FLTVideoPlayer installMovieNotificationObservers] in libflutter_ijk.a(FlutterIjkPlugin.o)
          -[FLTVideoPlayer removeMovieNotificationObservers] in libflutter_ijk.a(FlutterIjkPlugin.o)
      "_IJKMPMoviePlayerPlaybackDidFinishReasonUserInfoKey", referenced from:
          -[FLTVideoPlayer moviePlayBackFinish:] in libflutter_ijk.a(FlutterIjkPlugin.o)
      "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
          objc-class-ref in libflutter_ijk.a(FlutterIjkPlugin.o)
      "_IJKMPMoviePlayerLoadStateDidChangeNotification", referenced from:
          -[FLTVideoPlayer installMovieNotificationObservers] in libflutter_ijk.a(FlutterIjkPlugin.o)
          -[FLTVideoPlayer removeMovieNotificationObservers] in libflutter_ijk.a(FlutterIjkPlugin.o)
      "_IJKMPMediaPlaybackIsPreparedToPlayDidChangeNotification", referenced from:
          -[FLTVideoPlayer installMovieNotificationObservers] in libflutter_ijk.a(FlutterIjkPlugin.o)
          -[FLTVideoPlayer removeMovieNotificationObservers] in libflutter_ijk.a(FlutterIjkPlugin.o)
      "_IJKMPMoviePlayerPlaybackStateDidChangeNotification", referenced from:
          -[FLTVideoPlayer installMovieNotificationObservers] in libflutter_ijk.a(FlutterIjkPlugin.o)
          -[FLTVideoPlayer removeMovieNotificationObservers] in libflutter_ijk.a(FlutterIjkPlugin.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone X.
```

Steps to reproduce:

```
git pull https://github.com/jadennn/flutter_ijk.git
cd flutter_ijk/example
(run ios X simulator xCode 10.1, Mojave 10.14.2)
flutter run -d all
```

Any idea on this one?

**Comment by janiokq** [comment]
You need a complete IJK Media Framework.

**Comment by janiokq** [comment]
You need to compile the ijk framework yourself and add an output method for Pixelbuffe

- (CVPixelBufferRef)framePixelbuffer;
- (void)framePixelbufferLock;
- (void)framePixelbufferUnlock;

**Comment by ened** [comment]
@janiokq sorry what does that mean? The README file only specifies a package for pubspec.yaml. Does it mean IJK needs to be compiled separately>

**Comment by ened** [comment]
The issue may be coming from the way pub clones GIT repositories with LFS files, as done here.

The root cause to be fixed is https://github.com/dart-lang/pub/issues/1433 which adds support for correct fetch of LFS objects.

In the meantime, you can try cloning this repository instead: https://bitbucket.org/ivity/flutter_ijk_non_lfs.git
